# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://localhost:8080/survey
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTUzNjY3NjIzLCJleHAiOjE1NTQ1MzE2MjN9.bei_vwb47Q-7cvFrEmkRVzDOxU07Og0UXFJ9SaoLXQIzlQH2GYT1s89Bx8a7JTKzGfLj6HSTvmXIqSPVLlEang

{
  "title": "설문지",
  "description": "설문지 설명"
}

###

POST http://localhost:8080/survey/3/question
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTUzNjY3NjIzLCJleHAiOjE1NTQ1MzE2MjN9.bei_vwb47Q-7cvFrEmkRVzDOxU07Og0UXFJ9SaoLXQIzlQH2GYT1s89Bx8a7JTKzGfLj6HSTvmXIqSPVLlEang

{
  "no": 1,
  "content": "질문 1"
}

###

PUT http://localhost:8080/survey/1/question/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTUzNjY3NjIzLCJleHAiOjE1NTQ1MzE2MjN9.bei_vwb47Q-7cvFrEmkRVzDOxU07Og0UXFJ9SaoLXQIzlQH2GYT1s89Bx8a7JTKzGfLj6HSTvmXIqSPVLlEang

{
  "no": 1,
  "content": "질문 1",
  "type": "Objective",
  "objectiveItems": [],
  "id": 2,
  "createAt": "2019-03-28T15:32:28.200075",
  "modifyAt": "2019-03-28T15:32:28.200075"
}

###

GET http://localhost:8080/survey/my
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTUzNjY3NjIzLCJleHAiOjE1NTQ1MzE2MjN9.bei_vwb47Q-7cvFrEmkRVzDOxU07Og0UXFJ9SaoLXQIzlQH2GYT1s89Bx8a7JTKzGfLj6HSTvmXIqSPVLlEang

###
