# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

### 설문지 추가
POST http://localhost:8080/survey
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTU0MzYxODc3LCJleHAiOjE1NTUyMjU4Nzd9.EUVOErwQcHEiTvjG5GxrpgGasnCP8L7qjaTOKRLyCmUV4VSJdPKZ-8YfG2PnQMHOmnpS7dBCzX1pvryuWOeT0A

{
}

### 설문지 수정
PUT http://localhost:8080/survey
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTU0MzYxODc3LCJleHAiOjE1NTUyMjU4Nzd9.EUVOErwQcHEiTvjG5GxrpgGasnCP8L7qjaTOKRLyCmUV4VSJdPKZ-8YfG2PnQMHOmnpS7dBCzX1pvryuWOeT0A

{
  "id": 1,
  "title": "설문지 4",
  "description": "설문지 설명"
}

### 내 설문지 목록
GET http://localhost:8080/survey/my
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTU0MzYxODc3LCJleHAiOjE1NTUyMjU4Nzd9.EUVOErwQcHEiTvjG5GxrpgGasnCP8L7qjaTOKRLyCmUV4VSJdPKZ-8YfG2PnQMHOmnpS7dBCzX1pvryuWOeT0A

### 설문지 목록
GET http://localhost:8080/survey/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTU0MzYxODc3LCJleHAiOjE1NTUyMjU4Nzd9.EUVOErwQcHEiTvjG5GxrpgGasnCP8L7qjaTOKRLyCmUV4VSJdPKZ-8YfG2PnQMHOmnpS7dBCzX1pvryuWOeT0A

### 설문지 상세
GET http://localhost:8080/survey/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTU0MzYxODc3LCJleHAiOjE1NTUyMjU4Nzd9.EUVOErwQcHEiTvjG5GxrpgGasnCP8L7qjaTOKRLyCmUV4VSJdPKZ-8YfG2PnQMHOmnpS7dBCzX1pvryuWOeT0A


### 질문 추가
POST http://localhost:8080/survey/1/question?index=4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTU0MzYxODc3LCJleHAiOjE1NTUyMjU4Nzd9.EUVOErwQcHEiTvjG5GxrpgGasnCP8L7qjaTOKRLyCmUV4VSJdPKZ-8YfG2PnQMHOmnpS7dBCzX1pvryuWOeT0A

{
}

###

PUT http://localhost:8080/survey/1/question/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTU0MzYxODc3LCJleHAiOjE1NTUyMjU4Nzd9.EUVOErwQcHEiTvjG5GxrpgGasnCP8L7qjaTOKRLyCmUV4VSJdPKZ-8YfG2PnQMHOmnpS7dBCzX1pvryuWOeT0A

{
  "no": 1,
  "content": "질문 1",
  "type": "Subjective",
  "objectiveItems": [],
  "id": 1,
  "createAt": "2019-03-28T15:32:28.200075",
  "modifyAt": "2019-03-28T15:32:28.200075"
}

###
